DROP TABLE IF EXISTS audits CASCADE;
DROP TABLE IF EXISTS team_group_members CASCADE;
DROP TABLE IF EXISTS team_groups CASCADE;
DROP TABLE IF EXISTS team_members CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS user_identities CASCADE;
DROP TABLE IF EXISTS users CASCADE;