DROP TABLE IF EXISTS team_group_images CASCADE;
DROP TABLE IF EXISTS team_images CASCADE;
DROP TABLE IF EXISTS team_group_models CASCADE;
DROP TABLE IF EXISTS team_models CASCADE;
DROP TABLE IF EXISTS images CASCADE;
DROP TABLE IF EXISTS models CASCADE;
