// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Audit is the predicate function for audit builders.
type Audit func(*sql.Selector)

// GitBot is the predicate function for gitbot builders.
type GitBot func(*sql.Selector)

// GitBotTask is the predicate function for gitbottask builders.
type GitBotTask func(*sql.Selector)

// GitBotUser is the predicate function for gitbotuser builders.
type GitBotUser func(*sql.Selector)

// GitIdentity is the predicate function for gitidentity builders.
type GitIdentity func(*sql.Selector)

// Host is the predicate function for host builders.
type Host func(*sql.Selector)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// Model is the predicate function for model builders.
type Model func(*sql.Selector)

// NotifyChannel is the predicate function for notifychannel builders.
type NotifyChannel func(*sql.Selector)

// NotifySendLog is the predicate function for notifysendlog builders.
type NotifySendLog func(*sql.Selector)

// NotifySubscription is the predicate function for notifysubscription builders.
type NotifySubscription func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProjectCollaborator is the predicate function for projectcollaborator builders.
type ProjectCollaborator func(*sql.Selector)

// ProjectGitBot is the predicate function for projectgitbot builders.
type ProjectGitBot func(*sql.Selector)

// ProjectIssue is the predicate function for projectissue builders.
type ProjectIssue func(*sql.Selector)

// ProjectIssueComment is the predicate function for projectissuecomment builders.
type ProjectIssueComment func(*sql.Selector)

// ProjectTask is the predicate function for projecttask builders.
type ProjectTask func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskVirtualMachine is the predicate function for taskvirtualmachine builders.
type TaskVirtualMachine func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)

// TeamGroup is the predicate function for teamgroup builders.
type TeamGroup func(*sql.Selector)

// TeamGroupHost is the predicate function for teamgrouphost builders.
type TeamGroupHost func(*sql.Selector)

// TeamGroupImage is the predicate function for teamgroupimage builders.
type TeamGroupImage func(*sql.Selector)

// TeamGroupMember is the predicate function for teamgroupmember builders.
type TeamGroupMember func(*sql.Selector)

// TeamGroupModel is the predicate function for teamgroupmodel builders.
type TeamGroupModel func(*sql.Selector)

// TeamHost is the predicate function for teamhost builders.
type TeamHost func(*sql.Selector)

// TeamImage is the predicate function for teamimage builders.
type TeamImage func(*sql.Selector)

// TeamMember is the predicate function for teammember builders.
type TeamMember func(*sql.Selector)

// TeamModel is the predicate function for teammodel builders.
type TeamModel func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserIdentity is the predicate function for useridentity builders.
type UserIdentity func(*sql.Selector)

// VirtualMachine is the predicate function for virtualmachine builders.
type VirtualMachine func(*sql.Selector)
